import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { AddressInfo } from "node:net";
import {
  slicerSidecarAdapter,
  slicerSidecarSlice,
  SlicerSidecarError,
} from "./slicer-sidecar.js";

type Handler = (req: IncomingMessage, res: ServerResponse, body: Buffer) => void;

let server: Server;
let baseUrl: string;
let handler: Handler;
/** Requests the fake sidecar saw, for asserting what PP actually sent. */
let seen: Array<{ url: string; body: string }> = [];

function json(res: ServerResponse, status: number, payload: unknown): void {
  const text = JSON.stringify(payload);
  res.writeHead(status, { "content-type": "application/json" });
  res.end(text);
}

beforeAll(async () => {
  server = createServer((req, res) => {
    const chunks: Buffer[] = [];
    req.on("data", (c: Buffer) => chunks.push(c));
    req.on("end", () => {
      const body = Buffer.concat(chunks);
      seen.push({ url: req.url ?? "", body: body.toString("latin1") });
      handler(req, res, body);
    });
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const { port } = server.address() as AddressInfo;
  baseUrl = `http://127.0.0.1:${port}`;
});

afterAll(async () => {
  await new Promise<void>((resolve) => server.close(() => resolve()));
});

function reset(): void {
  seen = [];
}

const GCODE = "; generated by fake slicer\nG28\nG1 X10 Y10 F3000\n";
// 1x1 transparent PNG.
const PNG_B64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

describe("slicerSidecarSlice — v1 protocol", () => {
  it("posts file/slicer/resolved_flat_configs and decodes the base64 reply", async () => {
    reset();
    handler = (req, res) => {
      expect(req.url).toBe("/v1/slice");
      json(res, 200, {
        ok: true,
        meta: { slicer: "prusa", stub: false, duration_ms: 12, warnings: ["fyi"] },
        gcode_filename: "plate_1.gcode",
        gcode_base64: Buffer.from(GCODE).toString("base64"),
        thumbnail_filename: "plate_1.png",
        thumbnail_base64: PNG_B64,
      });
    };

    const result = await slicerSidecarSlice(
      { url: baseUrl, slicer: "prusa" },
      {
        model: new Uint8Array([0x50, 0x4b, 0x03, 0x04]),
        filename: "kit_prusa_xl_plate_01.3mf",
        slicer: "prusa",
        resolved_flat_configs: {
          machine: { printer_model: "XL" },
          process: { layer_height: "0.2" },
          filament: { filament_type: "PLA" },
        },
        timeout_s: 42,
      },
    );

    expect(Buffer.from(result.gcode).toString()).toBe(GCODE);
    // A real PNG signature, not just non-empty bytes.
    expect(Buffer.from(result.thumbnail.slice(0, 8))).toEqual(
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    );
    expect(result.filename).toBe("plate_1.gcode");
    expect(result.thumbnail_filename).toBe("plate_1.png");
    expect(result.protocol).toBe("v1");
    expect(result.warnings).toEqual(["fyi"]);

    const sent = seen[0]!;
    expect(sent.url).toBe("/v1/slice");
    expect(sent.body).toContain('name="slicer"');
    expect(sent.body).toContain("prusa");
    expect(sent.body).toContain('name="resolved_flat_configs"');
    expect(sent.body).toContain('"printer_model":"XL"');
    expect(sent.body).toContain('name="timeout_s"');
    expect(sent.body).toContain("42");
    expect(sent.body).toContain("kit_prusa_xl_plate_01.3mf");
  });

  it("surfaces the sidecar's structured error envelope", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 502, {
        ok: false,
        error: {
          code: "slicer_execution_failed",
          message: "orca-slicer exited with code 1.",
          details: { exit_code: 1, stderr: "bad 3mf" },
        },
      });
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca" },
        { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
      ),
    ).rejects.toMatchObject({
      code: "slicer_execution_failed",
      status: 502,
      message: "orca-slicer exited with code 1.",
    });
  });

  it("rejects an empty-gcode 200 rather than writing a zero-byte file", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 200, {
        ok: true,
        meta: { slicer: "orca", duration_ms: 1, warnings: [] },
        gcode_filename: "plate_1.gcode",
        gcode_base64: "",
        thumbnail_filename: "plate_1.png",
        thumbnail_base64: PNG_B64,
      });
    };

    const err = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca" },
      { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
    ).catch((e: unknown) => e);
    expect(err).toBeInstanceOf(SlicerSidecarError);
    expect((err as SlicerSidecarError).code).toBe("empty_gcode");
  });
});

describe("slicerSidecarSlice — legacy fallback", () => {
  it("retries /slice when /v1/slice is not implemented", async () => {
    reset();
    handler = (req, res) => {
      if (req.url === "/v1/slice") {
        res.writeHead(404, { "content-type": "text/plain" });
        res.end("Not Found");
        return;
      }
      json(res, 200, {
        gcode: Buffer.from(GCODE).toString("base64"),
        thumbnail: PNG_B64,
        filename: "plate_1.gcode",
      });
    };

    const result = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca" },
      {
        model: new Uint8Array([1]),
        slicer: "orca",
        resolved_flat_configs: {
          machine: { printer_model: "Voron350" },
          process: { layer_height: "0.2" },
          filament: { filament_type: "PLA" },
          filament_2: { filament_type: "PETG" },
        },
      },
    );

    expect(result.protocol).toBe("legacy");
    expect(Buffer.from(result.gcode).toString()).toBe(GCODE);
    expect(seen.map((s) => s.url)).toEqual(["/v1/slice", "/slice"]);

    // resolved_flat_configs must be split onto the legacy field names, with
    // every filament* key collected into the filament_configs array.
    const legacy = seen[1]!.body;
    expect(legacy).toContain('name="machine_config"');
    expect(legacy).toContain('name="process_config"');
    expect(legacy).toContain('name="filament_configs"');
    expect(legacy).toContain('"filament_type":"PLA"');
    expect(legacy).toContain('"filament_type":"PETG"');
  });

  it("does NOT fall back when the sidecar reports a real slicing failure", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 502, {
        ok: false,
        error: { code: "slicer_timeout", message: "timed out", details: {} },
      });
    };

    await expect(
      slicerSidecarSlice(
        { url: baseUrl, slicer: "orca" },
        { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
      ),
    ).rejects.toMatchObject({ code: "slicer_timeout" });
    // A 502 is the slicer failing, not a missing endpoint — retrying legacy
    // would slice twice and hide the real error.
    expect(seen.map((s) => s.url)).toEqual(["/v1/slice"]);
  });

  it("honours an explicit api=legacy pin without probing v1", async () => {
    reset();
    handler = (_req, res) => {
      json(res, 200, { gcode: Buffer.from(GCODE).toString("base64"), thumbnail: "" });
    };
    const result = await slicerSidecarSlice(
      { url: baseUrl, slicer: "orca", api: "legacy" },
      { model: new Uint8Array([1]), slicer: "orca", resolved_flat_configs: { machine: {} } },
    );
    expect(result.protocol).toBe("legacy");
    expect(seen.map((s) => s.url)).toEqual(["/slice"]);
  });

  it("rejects when no url is configured", async () => {
    await expect(
      slicerSidecarSlice({}, { model: new Uint8Array([1]), slicer: "orca" }),
    ).rejects.toMatchObject({ code: "no_url" });
  });
});

describe("slicerSidecarAdapter.testConnection", () => {
  it("passes against a v1 sidecar (/healthz)", async () => {
    reset();
    handler = (req, res) => {
      if (req.url === "/healthz") return json(res, 200, { ok: true });
      res.writeHead(404).end();
    };
    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "prusa" });
    expect(result.ok).toBe(true);
    expect(result.message).toContain("prusa");
    expect(result.message).toContain("v1");
  });

  it("passes against a legacy sidecar (/health only)", async () => {
    reset();
    handler = (req, res) => {
      if (req.url === "/health") return json(res, 200, { status: "ok" });
      res.writeHead(404).end();
    };
    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl, slicer: "orca" });
    expect(result.ok).toBe(true);
    expect(result.message).toContain("legacy");
  });

  it("fails when neither health endpoint answers", async () => {
    reset();
    handler = (_req, res) => {
      res.writeHead(500).end();
    };
    const result = await slicerSidecarAdapter.testConnection({ url: baseUrl });
    expect(result.ok).toBe(false);
  });

  it("fails cleanly with no url", async () => {
    const result = await slicerSidecarAdapter.testConnection({});
    expect(result.ok).toBe(false);
    expect(result.message).toContain("url is required");
  });
});
