import { describe, expect, it } from "vitest";
import { mkdtempSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { getDb, SqliteDatabase } from "../db/client.js";
import { AppRepository } from "../db/repository.js";
import {
  buildProfileSyncSettings,
  inferMaterialType,
  parseProfileFile,
  parseSlicerIni,
  parseSlicerJson,
  scalar,
  startProfileSyncWatcher,
} from "./profile-sync.js";

const ORCA_PROCESS = JSON.stringify({
  from: "User",
  inherits: "0.20mm Standard @MyRRF",
  layer_height: "0.24",
  name: "pp sync test 0.24mm",
  print_extruder_id: ["1"],
  print_extruder_variant: ["Direct Drive Standard"],
  print_settings_id: "pp sync test 0.24mm",
  version: "2.3.2.60",
});

const ORCA_FILAMENT = JSON.stringify({
  type: "filament",
  name: "Generic PLA @System",
  from: "system",
  filament_flow_ratio: ["0.98"],
  filament_retraction_length: ["0.8"],
  version: "2.3.2.60",
});

const PRUSA_PRINT_INI = `# generated by PrusaSlicer 2.8.0+linux-x64-GTK3 on 2026-08-17 at 00:53:59 UTC
layer_height = 0.22
first_layer_height = 0.35
perimeters = 3
infill_density = 20%
compatible_printers = 
inherits = 
`;

describe("profile-sync parsers", () => {
  it("scalar extracts strings/numbers/arrays/objects", () => {
    expect(scalar("0.2")).toBe("0.2");
    expect(scalar(3)).toBe("3");
    expect(scalar(["1"])).toBe("1");
    expect(scalar({ value: "x" })).toBe("x");
    expect(scalar(null)).toBeNull();
  });

  it("parses Orca JSON process profiles with array values flattened", () => {
    const flat = parseSlicerJson(ORCA_PROCESS);
    expect(flat.layer_height).toBe("0.24");
    expect(flat.print_extruder_id).toBe("1");
    expect(flat.version).toBe("2.3.2.60");
  });

  it("parses Prusa INI flat files, skipping comments", () => {
    const flat = parseSlicerIni(PRUSA_PRINT_INI);
    expect(flat.layer_height).toBe("0.22");
    expect(flat.first_layer_height).toBe("0.35");
    expect(flat.infill_density).toBe("20%");
    expect(flat["# generated"]).toBeUndefined();
  });

  it("parseProfileFile detects JSON format + version + name", () => {
    const parsed = parseProfileFile(ORCA_PROCESS, "process");
    expect(parsed.kind).toBe("process");
    expect(parsed.name).toBe("pp sync test 0.24mm");
    expect(parsed.version).toBe("2.3.2.60");
  });

  it("parseProfileFile detects Prusa INI format + version from header", () => {
    const parsed = parseProfileFile(PRUSA_PRINT_INI, "process");
    expect(parsed.kind).toBe("process");
    expect(parsed.version).toBe("2.8.0+linux-x64-GTK3");
  });

  it("parseProfileFile uses kindHint when type field is absent", () => {
    // Orca user saves omit `type`; directory must be authoritative.
    const parsed = parseProfileFile(ORCA_PROCESS, "process");
    expect(parsed.kind).toBe("process");
    // A filament file placed in a filament dir gets the filament kind.
    const fil = parseProfileFile(ORCA_FILAMENT, "filament");
    expect(fil.kind).toBe("filament");
  });

  it("infers material types from names", () => {
    expect(inferMaterialType("Generic PLA @System")).toBe("PLA");
    expect(inferMaterialType("Generic PETG")).toBe("PETG");
    expect(inferMaterialType("Some TPU 95A")).toBe("TPU");
    expect(inferMaterialType("Mystery Material")).toBe("Generic");
  });
});

describe("profile-sync watcher end-to-end", () => {
  it("watches a slicer dir and upserts a process profile, then broadcasts", async () => {
    const dir = mkdtempSync(join(tmpdir(), "pp-sync-db-"));
    const sqlite = new SqliteDatabase(dir);
    sqlite.connect();
    const repo = new AppRepository(getDb(sqlite), undefined, sqlite.reposDir);
    const base = mkdtempSync(join(tmpdir(), "pp-sync-root-"));
    const processDir = join(base, "user", "default", "process");
    mkdirSync(processDir, { recursive: true });

    try {
      const events: string[] = [];
      const handle = startProfileSyncWatcher(
        repo,
        {
          enabled: true,
          roots: [{ kind: "orca", baseDir: base, dirs: { process: "user/default/process" } }],
        },
        (e) => events.push(e.name),
      );

      // Let chokidar finish its initial scan before writing — writing immediately
      // after startProfileSyncWatcher() returns races chokidar's own readiness
      // and can silently drop the first "add" event under load.
      await new Promise((r) => setTimeout(r, 400));

      // Write a profile (simulating a slicer save).
      writeFileSync(join(processDir, "pp sync test 0.24mm.json"), ORCA_PROCESS);
      // Give chokidar + debounce time to fire.
      await new Promise((r) => setTimeout(r, 3000));

      const rows = repo
        .listProfileLibrary()
        .filter((r) => r.kind === "process" && r.slicerFormat === "orca");
      expect(rows.length).toBe(1);
      expect(rows[0]!.name).toBe("pp sync test 0.24mm");
      expect(rows[0]!.slicerFormat).toBe("orca");
      expect(rows[0]!.syncedFromSlicerVersion).toBe("2.3.2.60");
      expect(rows[0]!.lastSyncedAt).toBeTruthy();
      expect(rows[0]!.sourcePath).toContain("pp sync test 0.24mm.json");
      expect(events).toContain("pp sync test 0.24mm");

      // Re-save with a change (simulate edit) → same row upserted, version updated.
      writeFileSync(
        join(processDir, "pp sync test 0.24mm.json"),
        ORCA_PROCESS.replace('"0.24"', '"0.28"'),
      );
      await new Promise((r) => setTimeout(r, 3000));

      const after = repo
        .listProfileLibrary()
        .filter((r) => r.kind === "process" && r.slicerFormat === "orca");
      expect(after.length).toBe(1); // still one row — upsert, not duplicate
      expect(JSON.parse(after[0]!.resolvedFlatConfig ?? "{}").layer_height).toBe("0.28");

      handle.stop();
    } finally {
      sqlite.close();
      rmSync(base, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    }
  }, 15000);

  it("buildProfileSyncSettings skips unmounted volumes", () => {
    const settings = buildProfileSyncSettings({
      SLICER_ORCA_DIR: "/definitely/not/there",
      SLICER_PRUSA_DIR: "/also/missing",
      SLICER_BAMBU_DIR: "/nope/again",
    } as NodeJS.ProcessEnv);
    expect(settings.enabled).toBe(false);
    expect(settings.roots).toHaveLength(0);
  });
});
