import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import chokidar, { type FSWatcher } from "chokidar";
import type { AppRepository } from "../db/repository.js";
import { getLogger } from "./logger.js";
import {
  defaultWatchDirs,
  dialectToSyncKind,
  type SlicerDialect,
} from "./slicer-instances.js";

/**
 * profile-sync — watches the shared slicer config volumes for profile changes
 * saved via the slicer GUIs and upserts them into PP's slicer profile store.
 *
 * Layouts observed live (Aug 2026, verified against running containers):
 *   OrcaSlicer   /config/.config/OrcaSlicer/user/default/{process,machine,filament}/*.json
 *   BambuStudio  /config/.config/BambuStudio/user/default/{process,machine,filament}/*.json
 *   PrusaSlicer  /configs/.config/PrusaSlicer/{print,printer,filament}/*.ini
 *
 * Orca/Bambu write JSON; Prusa writes flat `key = value` INI. Orca/Bambu only
 * write on explicit Save or app close (not per keystroke), but a single save can
 * emit a burst of add/change events — we use chokidar's awaitWriteFinish
 * (800ms stability) plus a per-path debounce (1000ms) to collapse that burst
 * into a single upsert, per the original spec.
 */

export type SlicerKind = "orca" | "prusa" | "bambu";
export type ProfileKind = "printer" | "process" | "filament";

export type SlicerWatchRoot = {
  kind: SlicerKind;
  /** Absolute directory containing the slicer's per-user profile tree. */
  baseDir: string;
  /** Subdirectories under baseDir holding profile files, keyed by profile kind. */
  dirs: Partial<Record<ProfileKind, string>>;
};

export type ProfileSyncSettings = {
  roots: SlicerWatchRoot[];
  enabled: boolean;
};

export type ProfileSyncResult = {
  kind: ProfileKind;
  slicer: SlicerKind;
  name: string;
  version: string | null;
};

export type ProfileSyncEmitter = (event: ProfileSyncResult) => void;

const DEBOUNCE_MS = 1000;

/** Extract a scalar string from a raw slicer value (string, number, [x], {value}). */
export function scalar(raw: unknown): string | null {
  if (raw == null) return null;
  if (typeof raw === "string" || typeof raw === "number" || typeof raw === "boolean") {
    return String(raw);
  }
  if (Array.isArray(raw)) {
    return raw.length > 0 ? scalar(raw[0]) : null;
  }
  if (typeof raw === "object") {
    const v = (raw as Record<string, unknown>).value;
    return v != null ? scalar(v) : null;
  }
  return null;
}

/** Parse an Orca/Bambu JSON profile into a flat key -> string map. */
export function parseSlicerJson(raw: string): Record<string, string> {
  const obj = JSON.parse(raw) as Record<string, unknown>;
  const flat: Record<string, string> = {};
  for (const [k, v] of Object.entries(obj)) {
    const s = scalar(v);
    if (s !== null) flat[k] = s;
  }
  return flat;
}

/** Parse a Prusa `.ini` profile into a flat key -> string map (skip comments/blanks). */
export function parseSlicerIni(raw: string): Record<string, string> {
  const flat: Record<string, string> = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith(";")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (key) flat[key] = value;
  }
  return flat;
}

/** Best-effort material type from a filament profile name, defaulting to "Generic". */
export function inferMaterialType(name: string): string {
  const n = name.toUpperCase();
  const candidates = ["PLA", "PETG", "ABS", "ASA", "TPU", "PC", "NYLON", "PVA", "HIPS", "PCTG"];
  for (const c of candidates) {
    if (new RegExp(`\\b${c}\\b`).test(n)) return c;
  }
  return "Generic";
}

function firstNumber(flat: Record<string, string>, ...keys: string[]): number | null {
  for (const k of keys) {
    const v = flat[k];
    if (v == null) continue;
    const n = Number.parseFloat(v);
    if (Number.isFinite(n)) return n;
  }
  return null;
}

export type ParsedProfileFile = {
  kind: ProfileKind;
  name: string;
  version: string | null;
  flat: Record<string, string>;
};

/**
 * Parse a profile file on disk, detecting format (JSON vs INI) and kind.
 * `kindHint` disambiguates when the file has no explicit `type` field (Orca/Bambu
 * user saves omit it — the directory the file lives in is authoritative).
 */
export function parseProfileFile(raw: string, kindHint: ProfileKind): ParsedProfileFile {
  let flat: Record<string, string>;
  let version: string | null;
  const trimmed = raw.trimStart();
  if (trimmed.startsWith("{")) {
    flat = parseSlicerJson(raw);
    version = flat.version ?? null;
  } else {
    flat = parseSlicerIni(raw);
    const m = raw.match(/generated by\s+(?:PrusaSlicer|BambuStudio|OrcaSlicer)\s+([^\s]+)/i);
    version = m ? m[1] : null;
  }

  const kindRaw = (flat.type ?? "").toLowerCase();
  let kind = kindHint;
  if (kindRaw === "machine" || kindRaw === "printer") kind = "printer";
  else if (kindRaw === "process" || kindRaw === "print") kind = "process";
  else if (kindRaw === "filament") kind = "filament";

  const name = flat.name || flat.print_settings_id || "Unnamed";
  return { kind, name, version, flat };
}

/** Case-insensitive lookup of a profile file within a kind directory (returns path or null). */
function findProfileFile(
  baseDir: string,
  kindDir: string,
  name: string,
): string | null {
  const dirPath = join(baseDir, kindDir);
  let entries: string[];
  try {
    entries = readdirSync(dirPath);
  } catch {
    return null;
  }
  const wanted = name.toLowerCase();
  for (const entry of entries) {
    const base = entry.toLowerCase();
    if (base === `${wanted}.json` || base === `${wanted}.ini`) {
      return join(dirPath, entry);
    }
  }
  return null;
}

/**
 * Resolve a flat config by merging the (single-level) `inherits` parent for
 * Orca/Bambu JSON profiles. The parent file lives in the same kind directory,
 * named after the `inherits` string. If not found, returns the own flat map.
 */
function buildResolvedFlat(
  raw: string,
  own: Record<string, string>,
  kindDir: string,
  baseDir: string,
): Record<string, string> {
  if (!raw.trimStart().startsWith("{")) return own;
  const parentName = own.inherits;
  if (!parentName) return own;
  const parentPath = findProfileFile(baseDir, kindDir, parentName);
  if (!parentPath) return own;
  try {
    const parentFlat = parseSlicerJson(readFileSync(parentPath, "utf8"));
    // Own settings override inherited ones (slicers apply the chain the same way).
    return { ...parentFlat, ...own };
  } catch {
    return own;
  }
}

/**
 * Build watch roots from the container environment. When a slicer config volume
 * is not mounted (dir missing), that root is skipped. PP mounts them read-only:
 *   orca   -> /slicer-profiles/orca   (override: SLICER_ORCA_DIR)
 *   prusa  -> /slicer-profiles/prusa  (override: SLICER_PRUSA_DIR)
 *   bambu  -> /slicer-profiles/bambu  (override: SLICER_BAMBU_DIR)
 */
export function buildProfileSyncSettings(env: NodeJS.ProcessEnv): ProfileSyncSettings {
  const orcaBase = env.SLICER_ORCA_DIR?.trim() || "/slicer-profiles/orca";
  const prusaBase = env.SLICER_PRUSA_DIR?.trim() || "/slicer-profiles/prusa";
  const bambuBase = env.SLICER_BAMBU_DIR?.trim() || "/slicer-profiles/bambu";

  const roots: SlicerWatchRoot[] = [];

  if (existsSync(join(orcaBase, ".config", "OrcaSlicer", "user")) || existsSync(orcaBase)) {
    roots.push({
      kind: "orca",
      baseDir: orcaBase,
      dirs: {
        printer: ".config/OrcaSlicer/user/default/machine",
        process: ".config/OrcaSlicer/user/default/process",
        filament: ".config/OrcaSlicer/user/default/filament",
      },
    });
  }
  if (existsSync(join(prusaBase, ".config", "PrusaSlicer")) || existsSync(prusaBase)) {
    roots.push({
      kind: "prusa",
      baseDir: prusaBase,
      dirs: {
        printer: ".config/PrusaSlicer/printer",
        process: ".config/PrusaSlicer/print",
        filament: ".config/PrusaSlicer/filament",
      },
    });
  }
  if (existsSync(join(bambuBase, ".config", "BambuStudio", "user")) || existsSync(bambuBase)) {
    roots.push({
      kind: "bambu",
      baseDir: bambuBase,
      dirs: {
        printer: ".config/BambuStudio/user/default/machine",
        process: ".config/BambuStudio/user/default/process",
        filament: ".config/BambuStudio/user/default/filament",
      },
    });
  }

  return { enabled: roots.length > 0, roots };
}

const DIALECTS: ReadonlySet<string> = new Set(["orca_json", "bambu_json", "prusa_ini"]);

/**
 * Build watch roots from registered slicer instances (Slicer Hub).
 * Enabled rows with a non-empty watch_path become roots; missing dirs are still
 * included so first-time mounts work after the volume appears.
 */
export function buildProfileSyncSettingsFromInstances(
  instances: Array<{ enabled: boolean; dialect: string; watch_path: string }>,
): ProfileSyncSettings {
  const roots: SlicerWatchRoot[] = [];
  for (const instance of instances) {
    if (!instance.enabled) continue;
    const watchPath = instance.watch_path.trim();
    if (!watchPath) continue;
    if (!DIALECTS.has(instance.dialect)) continue;
    const dialect = instance.dialect as SlicerDialect;
    roots.push({
      kind: dialectToSyncKind(dialect),
      baseDir: watchPath,
      dirs: defaultWatchDirs(dialect),
    });
  }
  return { enabled: roots.length > 0, roots };
}

function upsert(
  repo: AppRepository,
  slicer: SlicerKind,
  parsed: ParsedProfileFile,
  raw: string,
  resolved: Record<string, string>,
  sourcePath: string,
): void {
  const resolvedJson = JSON.stringify(resolved);
  if (parsed.kind === "printer") {
    const nozzle = firstNumber(parsed.flat, "nozzle_diameter", "nozzle_diameter_mm");
    const extruders = firstNumber(parsed.flat, "extruder_count");
    repo.upsertSyncedPrinterProfile({
      name: parsed.name,
      slicerFormat: slicer,
      slicerVersion: parsed.version,
      nozzleDiameterMm: nozzle != null ? nozzle.toString() : null,
      extruderCount: extruders != null ? Math.trunc(extruders) : null,
      rawJson: raw.trimStart().startsWith("{") ? raw : null,
      resolvedFlatConfig: resolvedJson,
      sourcePath,
    });
  } else if (parsed.kind === "process") {
    repo.upsertSyncedProcessProfile({
      name: parsed.name,
      slicerFormat: slicer,
      slicerVersion: parsed.version,
      compatiblePrinters: parsed.flat.compatible_printers ?? null,
      resolvedFlatConfig: resolvedJson,
      sourcePath,
    });
  } else {
    const nozzle = firstNumber(
      parsed.flat,
      "nozzle_temperature",
      "nozzle_temperature_initial_layer",
      "temperature",
      "nozzle_temp_c",
    );
    const bed = firstNumber(
      parsed.flat,
      "bed_temperature",
      "bed_temperature_initial_layer",
      "bed_temp_c",
    );
    const fan =
      firstNumber(parsed.flat, "fan_pct", "cooling") ??
      (parsed.flat.fan_always_on === "1" ? 100 : null);
    repo.upsertSyncedFilamentProfile({
      name: parsed.name,
      materialType: inferMaterialType(parsed.name),
      slicerVersion: parsed.version,
      nozzleTempC: nozzle != null ? Math.round(nozzle) : null,
      bedTempC: bed != null ? Math.round(bed) : null,
      fanPct: fan != null ? Math.round(fan) : null,
      extrusionMultiplier:
        firstNumber(parsed.flat, "filament_flow_ratio", "extrusion_multiplier")?.toString() ?? null,
      pressureAdvance:
        firstNumber(parsed.flat, "pressure_advance", "filament_pressure_advance")?.toString() ?? null,
      retraction:
        firstNumber(parsed.flat, "filament_retraction_length", "retraction_length_mm")?.toString() ?? null,
      rawJson: raw.trimStart().startsWith("{") ? raw : null,
      rawIni: raw.trimStart().startsWith("{") ? null : raw,
      resolvedFlatConfig: resolvedJson,
      sourcePath,
    });
  }
}

/**
 * Start watching the configured slicer profile volumes. Returns a handle with
 * stop() and a manual `syncAll()` that scans and upserts every profile found
 * (useful at startup to pick up profiles saved before PP was running).
 */
export function startProfileSyncWatcher(
  repo: AppRepository,
  settings: ProfileSyncSettings,
  emit: ProfileSyncEmitter,
): { stop: () => void; syncAll: () => Promise<void> } {
  const log = getLogger();
  if (!settings.enabled || settings.roots.length === 0) {
    log.log("info", "[profile-sync] disabled — no slicer config volumes mounted");
    return { stop: () => {}, syncAll: async () => {} };
  }

  const pending = new Map<string, NodeJS.Timeout>();
  const watchers: FSWatcher[] = [];

  function schedule(filePath: string, fn: () => void): void {
    const existing = pending.get(filePath);
    if (existing) clearTimeout(existing);
    pending.set(
      filePath,
      setTimeout(() => {
        pending.delete(filePath);
        fn();
      }, DEBOUNCE_MS),
    );
  }

  function handleFile(absolute: string): void {
    const match = locate(absolute);
    if (!match) return;
    const { root, kind } = match;
    try {
      const raw = readFileSync(absolute, "utf8");
      const parsed = parseProfileFile(raw, kind);
      const resolved = buildResolvedFlat(raw, parsed.flat, root.dirs[kind] ?? "", root.baseDir);
      upsert(repo, root.kind, parsed, raw, resolved, absolute);
      emit({ kind: parsed.kind, slicer: root.kind, name: parsed.name, version: parsed.version });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log.log("warn", `[profile-sync] failed to parse ${absolute}: ${msg}`);
    }
  }

  for (const root of settings.roots) {
    const paths = Object.values(root.dirs)
      .filter((d): d is string => Boolean(d))
      .map((d) => join(root.baseDir, d));
    if (paths.length === 0) continue;
    const watcher = chokidar.watch(paths, {
      persistent: true,
      ignoreInitial: true,
      awaitWriteFinish: { stabilityThreshold: 800, pollInterval: 100 },
      depth: 2,
    });
    watcher.on("add", (p) => schedule(p, () => handleFile(p)));
    watcher.on("change", (p) => schedule(p, () => handleFile(p)));
    watcher.on("error", (e: unknown) => {
      const msg = e instanceof Error ? e.message : String(e);
      log.log("warn", `[profile-sync] watcher error: ${msg}`);
    });
    watchers.push(watcher);
    log.log("info", `[profile-sync] watching ${root.kind} under ${root.baseDir}`);
  }

  function locate(absolute: string): { root: SlicerWatchRoot; kind: ProfileKind } | null {
    for (const root of settings.roots) {
      for (const [kind, dir] of Object.entries(root.dirs) as Array<[ProfileKind, string | undefined]>) {
        if (!dir) continue;
        const dirPath = join(root.baseDir, dir);
        if (absolute.startsWith(dirPath + "/") || absolute === dirPath) {
          return { root, kind };
        }
      }
    }
    return null;
  }

  function syncAll(): Promise<void> {
    for (const root of settings.roots) {
      for (const dir of Object.values(root.dirs).filter((d): d is string => Boolean(d))) {
        if (!dir) continue;
        const dirPath = join(root.baseDir, dir);
        let entries: string[];
        try {
          entries = readdirSync(dirPath)
            .filter((e) => e.endsWith(".json") || e.endsWith(".ini"))
            .map((e) => join(dirPath, e));
        } catch {
          continue;
        }
        for (const f of entries) handleFile(f);
      }
    }
    return Promise.resolve();
  }

  return {
    stop() {
      for (const w of watchers) void w.close();
      for (const t of pending.values()) clearTimeout(t);
      pending.clear();
      log.log("info", "[profile-sync] stopped");
    },
    syncAll,
  };
}
